### ISSUE TITLE
Payment Configuration UI after setting STRAPI_ADMIN_API_TOKEN is Blank page

### ISSUE THREAD

**Issue by Amaan-Shaah** [manishkatyan/strapi-stripe#97]
Hi i have installed the stripe plugin for strapi  following the steps below:

Node version-v18.16.0
npm version -9.5.1
Strapi version - 4.6.1

1) installed package via yarn
2) Added the three keys to the .env file, Created a admin API token following steps in the docs and added the generated admin key to STRAPI_ADMIN_API_TOKEN . left the STRAPI_ADMIN_LIVE_STRIPE_SECRET_KEY & STRAPI_ADMIN_TEST_STRIPE_SECRET_KEY the same.

3) Built the UI with yarn build and ran yarn run develop, 
4) after logging in to the admin panel i can see the payments panel and clicking on configuration leads to a blank page,i am attaching the screenshots below.

Any help would be greatly appreciated.

![Screenshot from 2023-07-06 17-13-26](https://github.com/manishkatyan/strapi-stripe/assets/121847858/193365af-9a21-42a2-9eef-fe786e76005d)
![Screenshot from 2023-07-06 17-13-51](https://github.com/manishkatyan/strapi-stripe/assets/121847858/a420ef2b-f820-4fd3-9c2a-770b77c78a30)
![Screenshot from 2023-07-06 17-14-09](https://github.com/manishkatyan/strapi-stripe/assets/121847858/df314705-e9af-4ac9-b522-05358d06ed81)

**Comment by nishekh-e-r** [comment]
@Amaan-Shaah  For strapi version 4.6.1 please install this version [strapi-stripe-v3.3.0](https://www.npmjs.com/package/strapi-stripe/v/3.3.0).
Current strapi-stripe version 3.4.1 is not compatible with strapi-stripe 4.6.1.
Because Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting.
